# Site settings
title: NumberWorks Lab
email: krajcsi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Numerical cognition research and methodological works lab at ELTE, Budapest, Hungary.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.thenumberworks.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap

paginate: 3
paginate_path: "blog/page:num"
